//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDoChoi_369
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public string MaChiTiet { get; set; }
        public string MaHoaDon { get; set; }
        public string MaDoChoi { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DoChoi DoChoi { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
